{% set name = "xcfun" %}
{% set version = "2.1.0" %}
{% set sha256 = "64aac8c933cc129ce6326f3827e342abfd10b94ea4a302aaca9f10d342ad7656" %}
{% set pyver = PY_VER.replace(".", "") %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftlibs/xcfun/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # fix handling of include dirs within the build tree
    - patches/cmake_install_includedir.patch
    # allow to customize where the CMake config file will be installed
    - patches/install_cmakedir.patch
    # better handling of the folder structure for the Python module
    - patches/pymod_install_libdir.patch

build:
  number: {{ build }}
  skip: true  # [win and vc<14]
  binary_relocation: true
  run_exports:
    - {{ pin_subpackage('xcfun', max_pin='x.x') }}

requirements:
  build:
    - cmake >=3.14
    - {{ compiler('cxx') }}
    - pybind11 =*=*py{{ pyver }}*
    - ninja
  host:
    - python
  run:
    - numpy
    - python  # [win]

test:
  requires:
    - numpy
    - pytest
  imports:
    - xcfun
  commands:
    # Verify library
    - test -L $PREFIX/lib/libxcfun$SHLIB_EXT                                # [not win]
    - test -f $SP_DIR/xcfun/_xcfun*.so                                      # [not win]
    - if not exist %PREFIX%\\Library\\bin\\xcfun.dll exit 1                 # [win]
    - if not exist %PREFIX%\\Library\\lib\\xcfun.lib exit 1                 # [win]
    - if not exist %PREFIX%\\Lib\\site-packages\\xcfun\\_xcfun*.pyd exit 1  # [win]
    # Inspect linkage
    - ldd -v $PREFIX/lib/libxcfun$SHLIB_EXT                                 # [linux]
    - otool -L $PREFIX/lib/libxcfun$SHLIB_EXT                               # [osx]
    - conda inspect linkages --show-files --groupby=dependency $PKG_NAME    # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME                            # [osx]
    - ls -l $SP_DIR/xcfun                                                   # [not win]
    - dir %PREFIX%\\Lib\\site-packages\\xcfun                               # [win]
    - ldd -v $SP_DIR/xcfun/_xcfun*.so                                       # [linux]
    - otool -L $SP_DIR/xcfun/_xcfun*.so                                     # [osx]
    # Actually test
    - python -m pytest --pyargs xcfun

outputs:
  - name: xcfun
    files:
      - include/XCFun              # [not win]
      - lib/libxcfun*              # [not win]
      - share/cmake/XCFun          # [not win]
      - {{ SP_DIR }}/xcfun         # [not win]
      - Library\include\XCFun      # [win]
      - Library\bin\xcfun*         # [win]
      - Library\lib\xcfun*         # [win]
      - Library\share\cmake\XCFun  # [win]
      - Lib\site-packages\xcfun    # [win]

about:
  home: https://github.com/dftlibs/xcfun
  dev_url: https://github.com/dftlibs/xcfun
  doc_url: https://xcfun.readthedocs.io
  doc_source_url: https://github.com/dftlibs/xcfun/blob/master/doc/index.rst
  license: MPL-2.0
  license_url: https://opensource.org/licenses/MPL-2.0
  license_file: LICENSE.md
  license_family: MOZILLA
  summary: "Exchange-Correlation functionals with arbitrary order derivatives."

extra:
  recipe-maintainers:
    - robertodr
    - bast
